### PR TITLE
Revert StringIO change + fix (not unicode) strings

### PR DESCRIPTION
**Pull request by pbanaszkiewicz**
This pull request reverts "undoing" @wking's 0dae639 Py3-compatible change to StringIO.

Additionally, it fixes the errors that popped out during tests. The errors were about wrong type being passed to StringIO constructor as an argument: it was "str", should be "unicode".

### CODE REVIEW

**Comment by gvwilson** [comment]
So what winds up in the DB? UTF-8 encoded Unicode characters?  Does the rest of the application handle that?  Does it all display correctly, in all views, later?  (Because the other option is to stick to ASCII for this release.)

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 07:38:11AM -0800, Greg Wilson wrote:
> So what winds up in the DB? UTF-8 encoded Unicode characters?

Yes.  SQLite always uses UTF-8 for internal encoding [1].

> Does the rest of the application handle that?

Yup, Django natively supports Unicode data everywhere [2], and returns
results with headers specifying the charset (UTF-8 by default [3]).

That said, I prefer dropping 2.7 support or using the unicode_literals
__future__ [4] to landing this PR (or swcarpentry/amy#175).

[1]: https://docs.djangoproject.com/en/1.7/ref/unicode/#creating-the-database
[2]: https://docs.djangoproject.com/en/1.7/ref/unicode/
[3]: https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-DEFAULT_CHARSET
[4]: https://github.com/swcarpentry/amy/pull/175#issuecomment-72494560

**Comment by gvwilson** [comment]
On 2015-02-02 12:12 PM, W. Trevor King wrote:
> On Mon, Feb 02, 2015 at 07:38:11AM -0800, Greg Wilson wrote:
>  > So what winds up in the DB? UTF-8 encoded Unicode characters?
>
> Yes. SQLite always uses UTF-8 for internal encoding [1].
>

Good to know.

>  > Does the rest of the application handle that?
>
> Yup, Django natively supports Unicode data everywhere [2], and returns
> results with headers specifying the charset (UTF-8 by default [3]).
>

Django I trust - we're going to have to test that _our_ code doesn't 
break anything.

> That said, I prefer dropping 2.7 support

Nope.

> or using the unicode_literals
> __future__ [4] to landing this PR (or swcarpentry/amy#175).

+1 to from __future__ import unicode_literals - can you please push a PR 
against master so that we can merge right away, or do you want me to do it?
Thanks,
Greg

>
> [1]:
> https://docs.djangoproject.com/en/1.7/ref/unicode/#creating-the-database
> [2]: https://docs.djangoproject.com/en/1.7/ref/unicode/
> [3]:
> https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-DEFAULT_CHARSET
> [4]: https://github.com/swcarpentry/amy/pull/175#issuecomment-72494560
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gvwilson/amy/pull/13#issuecomment-72495691>.
>

-- 
Email longa, vita brevis.

**Comment by pbanaszkiewicz** [comment]
Hey @gvwilson 

You asked and it made me tinker more with these strings and I found I was wrong.

I found that on Python 2.7 there are *two* StringIO classes: one in `io` module, and one in `cStringIO` module.

On Python 2.7 we were defaulting to `io.StringIO` which causes pain…

All we had to do is change import order:
```python
# bad
try:
    from io import StringIO
except ImportError:
    from cStringIO import StringIO
from importlib import import_module

# good
try:
    from cStringIO import StringIO
except ImportError:
    from io import StringIO
from importlib import import_module
```

This is better than introducing unicode literals because it fixes the error at https://github.com/gvwilson/amy/blob/master/workshops/util.py#L26 - otherwise it cannot be fixed.

**Comment by gvwilson** [comment]
OK, so what we should do is add this:

try:
     from cStringIO import StringIO as AmyStringIO
except ImportError:
     from io import StringIO as AmyStringIO

to workshops/util.py, and then everything else can just:

from util import AmyStringIO

so that the conditional code is only needed in one place.  But see also 
the use of:

from __future__ import unicode_literals

(from https://github.com/gvwilson/amy/pull/13#issuecomment-72495691). 
Should we do both?

- G

On 2015-02-02 12:16 PM, Piotr Banaszkiewicz wrote:
> Hey @gvwilson <https://github.com/gvwilson>
>
> You asked and it made me tinker more with these strings and I found I
> was wrong.
>
> I found that on Python 2.7 there are /two/ StringIO classes: one in |io|
> module, and one in |cStringIO| module.
>
> On Python 2.7 we were defaulting to |io.StringIO| which causes pain…
>
> All we had to do is change import order:
>
> # bad
> try:
>      from  ioimport  StringIO
> except  ImportError:
>      from  cStringIOimport  StringIO
> from  importlibimport  import_module
>
> # good
> try:
>      from  cStringIOimport  StringIO
> except  ImportError:
>      from  ioimport  StringIO
> from  importlibimport  import_module
>
> This is better than introducing unicode literals because it fixes the
> error at
> https://github.com/gvwilson/amy/blob/master/workshops/util.py#L26 -
> otherwise it cannot be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gvwilson/amy/pull/13#issuecomment-72496508>.
>

-- 
Email longa, vita brevis.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 09:16:55AM -0800, Piotr Banaszkiewicz wrote:
> I found that on Python 2.7 there are *two* StringIO classes: one in
> `io` module, and one in `cStringIO` module.
> 
> On Python 2.7 we were defaulting to `io.StringIO` which causes pain…

Ah, I didn't realize that io.StringIO works for Python 2 as well [1].
That means we can just use:

  from io import StringIO

for all Pythons.

> This is better than introducing unicode literals because it fixes
> the error at
> https://github.com/gvwilson/amy/blob/master/workshops/util.py#L26 -
> otherwise it cannot be fixed.

The Django docs linked from the docstring [2] says “Python 2’s csv
module does not support Unicode input” and suggests a few
alternatives.  Personally, I'd rather drop Python 2 support (I still
see no reason why we *want* to support Python 2).  Of the other
alternatives, using python-unicodecsv sounds best, since then we have
no internal code to maintain in amy (which shouldn't be caring about
low-level stuff like this).

[1]: https://docs.python.org/2/library/io.html#io.StringIO
[2]: https://docs.djangoproject.com/en/1.7/howto/outputting-csv/#using-the-python-csv-library

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 09:20:30AM -0800, Greg Wilson wrote:
> OK, so what we should do is add this:
> 
> try:
>      from cStringIO import StringIO as AmyStringIO
> except ImportError:
>      from io import StringIO as AmyStringIO

I see no need to use cStringIO, define a local UnicodeWriter, or
rename from StringIO to AmyStringIO.

> … so that the conditional code is only needed in one place.

It's not much conditional code, and dropping UnicodeWriter should let
us use:

  from io import StringIO

everywhere (for all Pythons).  I think renaming to AmyStringIO is
going to confuse new readers.

> from __future__ import unicode_literals

I'd recommend this, regardless of what we do with the StringIO bits.

**Comment by gvwilson** [comment]
Wasn't aware that 'from io import StringIO' would work in P2.7.  Will 
that plus unicode_literal solve our problems?

On 2015-02-02 12:36 PM, W. Trevor King wrote:
> On Mon, Feb 02, 2015 at 09:20:30AM -0800, Greg Wilson wrote:
>  > OK, so what we should do is add this:
>  >
>  > try:
>  > from cStringIO import StringIO as AmyStringIO
>  > except ImportError:
>  > from io import StringIO as AmyStringIO
>
> I see no need to use cStringIO, define a local UnicodeWriter, or
> rename from StringIO to AmyStringIO.
>
>  > … so that the conditional code is only needed in one place.
>
> It's not much conditional code, and dropping UnicodeWriter should let
> us use:
>
> from io import StringIO
>
> everywhere (for all Pythons). I think renaming to AmyStringIO is
> going to confuse new readers.
>
>  > from __future__ import unicode_literals
>
> I'd recommend this, regardless of what we do with the StringIO bits.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gvwilson/amy/pull/13#issuecomment-72500268>.
>

-- 
Email longa, vita brevis.

**Comment by pbanaszkiewicz** [comment]
From what I understand we need:
```python
from io import StringIO
```

plus
```python
from __future__ import unicode_literals
```

plus `python-unicodecsv`.

From my testing, unicode_literals were required for `io.StringIO` but not for `cStringIO.StringIO`.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 09:39:05AM -0800, Greg Wilson wrote:
> Wasn't aware that 'from io import StringIO' would work in P2.7.
> Will that plus unicode_literal solve our problems?

No, because Python 2's csv module doesn't support Unicode strings
[1,2,3].  My preferred solution there is to drop Python 2 or use
python-unicodecsv [1].

[1]: https://github.com/gvwilson/amy/pull/13#issuecomment-72499691
[2]: https://docs.djangoproject.com/en/1.7/howto/outputting-csv/#using-the-python-csv-library
[3]: https://docs.python.org/2/library/csv.html

**Comment by gvwilson** [comment]
https://github.com/jdunck/python-unicodecsv for python-unicodecsv ?  If 
so, +1.
G

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 09:44:19AM -0800, Greg Wilson wrote:
> https://github.com/jdunck/python-unicodecsv for python-unicodecsv ?

Yup [1].  But I think we should wait here until we hear if dropping
Python 2 is acceptable [2].  No sense in working around an outdated
stdlib issue if we can just use a modern stdlib ;).

[1]: https://pypi.python.org/pypi/unicodecsv/0.9.4
[2]: https://github.com/swcarpentry/amy/pull/175#issuecomment-72498105

**Comment by gvwilson** [comment]
On 2015-02-02 12:48 PM, W. Trevor King wrote:
> On Mon, Feb 02, 2015 at 09:44:19AM -0800, Greg Wilson wrote:
>  > https://github.com/jdunck/python-unicodecsv for python-unicodecsv ?
>
> Yup [1]. But I think we should wait here until we hear if dropping
> Python 2 is acceptable [2]. No sense in working around an outdated
> stdlib issue if we can just use a modern stdlib ;).
>

I prefer to keep using Py2.7 until we switch our lessons over, which 
isn't going to happen until mid-summer at the earliest.

**Comment by wking** [comment]
On Mon, Feb 02, 2015 at 10:07:17AM -0800, Greg Wilson wrote:
> On 2015-02-02 12:48 PM, W. Trevor King wrote:
> > On Mon, Feb 02, 2015 at 09:44:19AM -0800, Greg Wilson wrote:
> > > https://github.com/jdunck/python-unicodecsv for python-unicodecsv ?
> >
> > Yup [1]. But I think we should wait here until we hear if dropping
> > Python 2 is acceptable [2]. No sense in working around an outdated
> > stdlib issue if we can just use a modern stdlib ;).
> 
> I prefer to keep using Py2.7 until we switch our lessons over, which 
> isn't going to happen until mid-summer at the earliest.

I understand wanting backwards compatibility for the lessons, since
they have a huge audience of both instructors and students.  Amy, on
the other hand, only matters to a handful of devs and will only be
deployed in a single location.  I don't see a reason to tie it to old
Pythons, especially since migrating to Python-3-only solves some
Unicode headaches.

**Comment by pbanaszkiewicz** [comment]
Because we moved to Python3 I'm closing this one.

**Pull request closed without merging**
